import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar.js"
import SideDashBar from "./components/dasboard_components/SideDashBar"
import DashHeading from "./components/dasboard_components/DashHeading"
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BEBASTHA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,  
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (  
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
       <NavBar />
      <div className='h-[calc(100vh-57.33px)] flex-1 flex w-full' >  
                <SideDashBar />
              <div className='bg-gray-100 flex-1 overflow-auto'>
                <DashHeading />
              {children}
              <Toaster position="top-right" richColors />
              </div>
          </div>

        
      </body>
    </html>
  );
}
